/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_eclic.h>
#elif defined(CONFIG_SOC_SERIES_GD32VW55X)
#include <gd32vw55x_eclic.h>
#endif
